export const nakedManPhotosModalImageTexts = [
  "Pillars at Naked Man Beach. Dated - 2021",
  "Sandbar at beach. Dated - 2021",
  "Hikers walking the beach. Dated - 2021",
  "Pillars at the sandbar. Dated - 2021",
  "Looking up the coast towards the bacon strip from sandbar. Dated - 2022",
  "Rock pillars at beach. Dated - 2022",
  "Looking out across Bonavista Bay from trail. Dated - 2022",
  "View of sandbar on beach from Hogan's Lookout. Dated - 2021",
  "Hiking trail and viewing Bonavista Bay. Dated - 2020",
  "Hiking. Dated - 2021",
  "View from Hogan's Lookout. Dated - 2020",
  "Looking across Bonavista Bay. Dated - 2021",
  "Hiking in nature. Dated - 2021",
  "Hiking. Dated - 2021",
  "Watching small iceberg from Hogan's Lookout. Dated - 2022",
  "Iceberg and pillars. Dated - 2022",
  "Looking up the beach. Dated - 2021",
  "Sunset at the beach. Dated - 2021",
  "Bay view. Dated - 2020",
  "Starting your hike. Dated - 2020",
  "Beach view. Dated - 2021",
  "Hiking across a creek. Dated - 2020",
  "Enjoy the sandy beach. Dated - 2021",
  "Pillars. Dated - 2020",
  "Ocean view. Dated - 2021",
  "Small waterfall at beach. Dated - 2022",
  "Viewing the beach from boat. Dated - Early 1990's",
  "Coastal view with beach. Dated - Early 1990's",
  "Naked Man Beach. Dated - Early 1990's",
  "Arial view of the beach. Dated - 2018",
  "Naked Man pillar. Dated - 2019",
  "Cute bird houses on trail. Dated - 2022",
  "Viewing the cave and beach from a boat. Dated - 2021",
  "Cave on the beach. Dated - 2019",
  "View out of shallow cave on beach. Dated - 2021",
  "Beautiful sunset at Hogan's Lookout. Dated - 2020",
  "Coastal views. Dated - 2021",
  "Waves crashing on the beach. Dated - 2020",
  "Cloudy day at the beach. Dated - 2020",
  "Hogan's Lookout over beach. Dated - 2021",
  "Memory bench and picnic table to view across Bonavista Bay. Dated - 2021",
  "Stormy day with waves at the pillars. Dated - 2021",
  "Sit to have a snack and enjoy the view (Pack it in / Pack it out). Dated - 2021",
  "Highway trail sign. Dated - 2021",
  "Trail sign. Dated - 2021",
  "Memory bench with a view. Dated - 2021",
  "Pillars as you come back from the sandbar to form a naked man sitting down with his legs out (where name of beach came from). Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the ocean from bench. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
  "Viewing the frozen winter scene. Dated - 2021",
  "Viewing the sandbar at low tide. Dated - 2021",
];

export const butchersNosePhotosModalImageTexts = [
  "Trail sign. Dated - 2021",
  "Top of Butcher's Nose overlooking Bald Rock Point with Plate Cove West in the background. Dated - 2021",
  "Viewing Plate Cove East from the top. Dated - 2021",
  "Looking across the cove into Bonavista Bay. Dated - 2021",
  "Looking to Plate Cove West from the top. Dated - 2021",
  "Direction sign on trail. Dated - 2021",
  "Trail sign showing the start of incline on trail. Dated - 2021",
  "Arial view of Bald Rock Point and Plate Cove West in background. Dated - 2021",
  "Hiking with your pet on a leash to enjoy the views. Dated - 2021",
  "Enjoy a break while hiking (Pack it in, Please pack it out!). Dated - 2021",
  "Painted rock with words of encouragement. Dated - 2021",
  "View over the western side of the cove. Dated - 2021",
];

export const churchHistoryPhotosModalImageTexts = [
  "Church on the right was the first church built around 1930 that was replaced with a larger church in the 1950's (left in the picture) Plate Cove East.",
  "Church when it was originally built in the 1950's with the tower which was later removed when the parish decided to hang the bell on a smaller tower close to the church. Plate Cove East",
  "Viewing Plate Cove church while boating. Plate Cove East - Dated early 1980's",
  "The way the church and tower looked at the time it was destroyed by fire. Plate Cove East - Dated 1986.",
  "Present day church with it's modern style that was built around 1990. The new church houses the church, a chapel, community center, fully equiped kitchen, stage for christmas / st. patrick's day concerts and his/her washrooms. Plate Cove - Dated - 2020",
];

export const jigginHeadPhotosModalImageTexts = [
  "Trail sign with rules to start your hike. Dated - 2022",
  "Trail markers to follow on trail. Dated - 2022",
  "Start your hike out to the lookout. Dated - 2022",
  "Stop for a snack on your hike. (If you pack it in, please pack it out.). Dated - 2022",
  "Relax with a view over parts of Summerville and Bovavista Bay. Dated - 2022",
  "Viewing the fjords in Bonavista Bay. Dated - 2022",
  "Beautiful Bonavista Bay. Dated - 2022",
  "View of the hills of the Plate Cove volcanic belt looking at the beginning of Plate Cove West. Dated - 2022",
  "Viewing Rattling Pond and the beginning of Plate Cove West. Dated - 2022",
  "Hiking during the fall. Dated - 2022",
  "Relax on a memory bench while hiking on trail. Dated - 2022",
  "Rocks of the Plate Cove volcanic belt at the top. Dated - 2022",
  "Rest at the top to enjoy the arial view. Dated - 2022",
  "Lookout over Summerville. Dated - 2022",
  "The finish line at top of trail. Dated - 2022",
];

export const plateCoveHistoryPhotosModalImageTexts = [
  "Keough family mill towards the point located in Plate Cove West. Dated - 1984",
  "As you enter Plate Cove East. Dated - 1984",
  "Stripping logs for repairs to slipway located in Plate Cove East. Dated - 1984",
  "Stripping Logs for repairs to slipway located in Plate Cove West. Dated - 1984",
  "Bill Mews (left) & Bill Walsh in Plate Cove West. Dated - 1984",
  "Motor boats on the slipway in Plate Cove East. Dated - 1984",
  "Picture of the community and both older churches of Plate Cove on the hill. Plate Cove East. Dated - late 1950's",
  "Original Cabot Highway travelling from Butcher's Nose into Plate Cove West. In the picture you will see schooner's and you will notice the stages with sheds that are no longer there due to storm surges over the years. Dated - 1947",
  "Gravel road leading into Plate Cove West. Dated - 1947",
  "The original Cabot Highway at Plate Cove East. Note the narrowness of the road, the fenced gardens, the horse crossing the road and the old telegrapgh pole with the glass insulator and 'bottle stick'. Dated - 1947",
  "Official opening of the highway was in the late 1940's. Driving in the path end section leading into Plate Cove West.",
  "Thomas (Mr. Tommy) Keough's wharf & shed. Plate Cove West. Dated - 1947",
  "Looking towards Bald Rock Point with vehicles in the foreground. Plate Cove East. Dated - Late 1970's to early 1980's",
  "Standing at a fence by Annie Dooley's house looking across the cove. You can notice the Plate Cove church on the hill by the lower chimney. Plate Cove East. Dated - 1980",
  "Daniel Keough's motorboat being launched on Bayview Drive (formely known as the back lane). Wife - Ellen (braker) Keough upper middle of picture in white dress. Genevieve Furlong to the right of Ellen Keough (4th. to the right in a dress). Plate Cove West - Dated - 1960's",
];

export const plateCovePhotosModalImageTexts = [
  "Butcher's Nose Lookout with Plate Cove East in the foreground and Plate Cove West in the background. Dated - 2021",
  "View from main road of wharf with iceberg in the distance. Plate Cove West. Dated - 2022",
  "View of wharf and boats in Plate Cove West. Dated - 2022",
  "Donated memory sign, bench and planters located in Plate Cove West. Dated - 2022",
  "Plate Cove pool loacted in Plate Cove East with views of both East and West sides of the cove. Dated - 2020",
  "Relax at Plate Cove pool located in Plate Cove East. Dated - 2020",
  "Donated community sign with benches and planters loacted in Plate Cove West. Dated - 2023",
  "Looking at homes and the cove in Plate Cove East. Dated - late 1980's",
  "Root vegtables were grown ever since the area was settled in the early 1800's. Herbert Keough preparing his garden for another years growing season located Plate Cove West. Dated - 2021",
  "Boat ride in the cove with a view of Plate Cove West. Dated - early 1990's",
  "View from hill of Bald Rock Point in Plate Cove East. Plate Cove church upper right and Plate Cove West in the foregrown. Dated - early 1990's",
  "View looking at both sides of the cove. Plate Cove East in the background and Plate Cove West in the foreground. Dated - early 1990's",
  "Looking from a hill behind Plate Cove West over looking both the West and East sides with Open Hall and Red Cliff up the coast in the background. Dated - early 1990's",
  "Looking from Plate Cove West up Bonavista Bay towards Open Hall. Dated - early 1990's",
  "View of the wharf and beach area of Plate Cove West - Dated - early 1990's",
  "Hiking Butcher's Nose you have a great view of the cove with Bald Rock Point and along the coast to Plate Cove West in the background. Dated - 2022",
  "Fishing boat traveling around an iceberg in Plate Cove",
  "Looking from Bald Rock Point in Plate Cove East at the ice and the icebergs with Plate Cove West in the background. Dated - early 2000's",
  "Speed boat picking a path around the icebergs in Plate Cove. Dated - early 2000's",
  "Donald and Lou Fennell have their picture taken with icebergs just outside Plate Cove with Open Hall in the background. Dated - 2010",
  "Iceberg in Plate Cove. Dated - 2022",
  "Beach at Plate Cove West before Hurricane Igor. Dated - early 2000's",
  "Wharf repairs in Plate Cove West. Dated - early 2000's",
  "View of wharf and Plate Cove West. Dated - early 1990's",
  "Looking across the cove at Bald Rock Point and Butcher's Nose in Plate Cove East. Dated - 2021",
  "Kids enjoying the Plate Cove infinity pool located in Plate Cove East. Dated - 2020",
  "The boats of Plate Cove fishing at sunset. Dated - 2018",
  "Fishing for caplin in Plate Cove. Dated - 2019",
  "Long liners fishing in Plate Cove. Dated - 2019",
  "Boats fishing in Plate Cove while the whales swimming around them as you can see one whale blow in the foreground. Dated - 2019",
  "Long liners fishing in Plate Cove with Plate Cove East in the background. Dated - 2019",
  "Caplin fishing of Red Beach at Plate Cove West Head. Dated - 2019",
  "Boats tied up waiting to go fishing in the morning. Plate Cove West. Dated - 2020",
  "Lots of boats done from a day of fishing in Plate Cove West. Dated - 2020",
  "Boats and fishing gear all ready to go fishing the next day. Plate Cove West. Dated - 2020",
  "Long liners and speed boats all tied up from a day of fishing. Plate Cove West. Dated - 2020",
  "Plate Cove pool all ready for swimming in Plate Cove East. Dated - 2019",
  "Looking across the cove at Bald Rock Point in Plate Cove East from Plate Cove West. Dated - 2021",
  "Potatoes are grown in Plate Cove yearly by some families. Plate Cove West. Dated - 2021",
  "Folks growing a variety of vegetables in Plate Cove West. Dated - 2021",
  "Lots of potatoes in the garden. Plate Cove West. Dated - 2021",
  "Harvesting his potato crop, Herbert Keough digs the potatoes to store in his root cellar for the winter. Plate Cove West. Dated - 2021",
  "Double rainbows over Plate Cove and the Catholic Church. Plate Cove West. Dated - 2021",
  "Looking over Bald Rock Point and Plate Cove West in the background. Plate Cove East. Dated - 2019",
  "Sundog over Plate Cove. Plate Cove West in the background and Plate Cove East in the foreground. Dated - 2022",
  "Boats on slipway for winter. Plate Cove East. Dated - 2022",
  "Beautiful sky during sunset over Plate Cove. Plate Cove East. Dated - 2021",
  "Locals with a view. Plate Cove East. Dated - 2021",
  "Aiden and Mary(Whalen) Keough's home in Plate Cove West. Built late 1960's but was removed in early 2000's due to moisture damage when home wasn't used.",
  "View the cove with Plate Cove West in the background and Plate Cove East in the foreground. Dated - early 2000's",
  "Community sign and planters on the beach in Plate Cove West. Dated - 2022",
  "View a boat leaving the cove with Plate Cove West in the background. Taken from Plate Cove Church. Dated - early 2000's",
  "Viewing Plate Cove West wharf from Plate Cove Church. Dated - early 2000's",
  "Boats and wharf in the fall. Plate Cove West. Dated - 2019",
  "Boats on the slipway for the winter in Plate Cove West. Dated - 2022",
  "Waiting for Spring to go in the water for fishing. Plate Cove West. Dated - 2022",
  "Looking at the size of these long liners on the slipway. Plate Cove West. Dated - 2022",
  "Boats moored in the cove with some wood for wood stove and houses over looking the cove. Plate Cove East. Dated - 2020",
  "Looking from the Plate Cove Church at Plate Cove West. Dated - 2021",
  "Sun setting over Plate Cove with Plate Cove East in the foreground. Dated - 2021",
  "Ice packed in Plate Cove with an iceberg in the bay. Dated - 2023",
  "Viewing pack ice, iceberg and an eagle with Plate Cove West in the background. Dated - 2023",
  "Watching Faye and Terry Fitzgerald's boat (called the Shane & Shannon) pass by an iceberg. Bonavista Bay. Dated - 2020",
  "Putting your boat in the pool to race. Plate Cove East. Dated - 2022",
  "On your mark, ready & go! at the Plate Cove pool. Plate Cove East. Dated - 2022",
  "Racing to win at the Plate Cove pool. Plate Cove East. Dated - 2022",
  "Race your boat at the pool. Plate Cove East. Dated - 2022",
  "Traditional Newfoundland biscuit house and sunset. Plate Cove East. Dated - 2022",
  "Northern Lights over Plate Cove. Picture taken from the beach in Plate Cove West. Dated - 2023",
  "Arial view of Plate Cove East. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
  "Arial view of Plate Cove West. Dated - Early 1990's",
];

export const plateCodeResidentsPhotosModalImageTexts = [
  "Mary (Philpott) Hyde, Mary (Heaney) Keough and Mary (Whalen) Keough. Plate Cove West.",
  "From left to right. Terry Keough, Mary Ellen (Keough) Heaney, Fred Keough, (next 4 people unknown). Top left to right is Mary (Heaney) Keough and Ellen (Braker) Keough. Plate Cove West.",
  "Herbert Keough and family horse. Plate Cove West",
  "Ellen (Braker) Keough in Plate Cove West.",
  "Herbert Keough and Fred Keough enjoying a horse ride in Plate Cove West.",
  "James (Jim) Furlong. Plate Cove West. Dated - 1980's",
  "Patrick Furlong (Pa), Genevieve (Genever) Furlong and son James (Jim) Furlong. Plate Cove West.",
  "Ellen (Braker) (aka Mother) Keough. Plate Cove West. Dated - Late 1980's",
  "Margaret (Furlong) Dooley. Plate Cove East.",
  "James Furlong (left)",
  "Mary (Whalen) Keough, Shirley (brothers) Keough and Johanna (Furlong) Keough. Plate Cove West.",
  "Trina Keough. Plate Cove West. Dated - 1995",
  "Cecelia (Keough) Philpott. Plate Cove West",
  "Pius Keough. Plate Cove West.",
  "Owen Keough. Plate Cove West.",
  "Mary (Keough) Heaney, Herbert Keough, Anastasia (Keough) Gillingham and Regina (Keough) Furlong. Plate Cove West.",
  "Michael Francis Furlong, Daniel Keough, Ellen (Braker) Keough and Nellie (Keough) Furlong. Plate Cove West.",
  "Johanna (Furlong) Keough. Plate Cove West.",
  "Ellen (Braker) Keough and Daniel Keough. Plate Cove West.",
  "Top left to right. Daniel Keough, Fred Keough, Terry Keough, Mary (Keough) Heaney, Patrick Keough, Jerome Keough, Samual Keough, Bottom left to right. Anastasia (Keough) Gillingham, Aiden Keough, Herbert Keough, Regina (Keough) Furlong and Pierce Keough. Plate Cove West.",
  "Top left to right. Herbert Keough, Johanna (Furlong) Keough, bottom left to right. Warren Keough, Owen Keough and Faye (Keough) Fitzgerald. Plate Cove West.",
  "Listed in photo are Jim, Mary, Dan, Donald, Angela, Jose, Fred and Mother Keough.",
  "Thomas Leo Furlong (aka Tom Leo) right & Catherine Blanche Furlong (nee Walsh) known to all as Blanche or 'Mudder'. Plate Cove West. Dated - 1984/85",
];

export const redBeachPhotosModalImageTexts = [
  "Walking on Red Beach. Dated - 2021",
  "Looking at Bonavista Bay and Red Beach with a memory bench. Dated - 2021",
  "Pius Keough memorial at Red Beach Lookout. Dated - 2022",
  "Red Beach and Bonavista Bay. Dated - 2021",
  "Viewing Red Beach from Furlong's Lookout. Dated - 2022",
  "Hiking Red Beach as you pass through Keough's garden. Dated - 2022",
  "Hiking to Red Beach. Dated - 2021",
  "Seeing the ocean close to Red Beach. Dated - 2022",
  "Sign showing the way to Red Beach. Dated - 2022",
  "Hiking to Red Beach. Dated - 2020",
  "Looking down the creek to Red Beach. Dated - 2021",
  "Hiking on Red Beach trail. Dated - 2020",
  "Painted trail sign. Dated - 2020",
  "Viewing the cliffs at Red Beach with a memory bench. Dated - 2020",
  "Red Beach trail sign.",
  "Ocean rolling at the beach. Dated - 2020",
  "Viewing Red Beach from boat. Dated - early 1990's",
  "Viewing Red Beach with memorial bench. Dated - 2020",
  "Highway direction sign to Red Beach. Dated - 2021",
  "Trail sign for Red Beach. Dated - 2021",
  "Red sand and red cliffs at Red Beach. Dated - 2021",
  "Face in cliff meeting the ocean with someone relaxing on the beach. Dated - 2021",
  "Memory bench at Furlong's Lookout. Dated - 2021",
  "Enjoying the views from Furlong's Lookout. Dated - 2021",
  "Sunsets at the beach. Dated - 2021",
  "Thunder storm clouds coming with the sun, giving the clouds an amazing colour. Dated - 2021",
  "Beautiful sunset while looking out Bonavista Bay. Dated - 2021",
  "Stormy day at the beach. Dated - 2022",
  "Creek view of beach and Bonavista Bay. Dated - 2021",
  "Enjoying beach life. Dated - 2021",
  "Speeding away from the beach. Dated - 2019",
  "Viewing Bonavista Bay from memorial. Dated - 2022",
  "Possible to see pigs at the Keough hobby farm while hiking. Dated - 2022",
  "Pigs on the hobby farm as your hike the trail. Dated - 2022",
  "Memorial and memory bench. Dated - 2022",
  "Viewing the beach from Furlong's Lookout. Dated - 2021",
  "Boat coming to the beach. Dated - 2022",
  "Memory benches and picnic table to relax and enjoy the views. Dated - 2022",
  "Watching boats and seadoos. Dated - 2022",
  "View Red Beach Lookout. Dated - 2021",
  "View Red Beach Lookout. Dated - 2021",
  "View Red Beach Lookout. Dated - 2021",
  "View Red Beach Lookout. Dated - 2021",
  "View Red Beach Lookout. Dated - 2021",
  "View Red Beach Lookout. Dated - 2021",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
  "View Red Beach Lookout. Dated - 2023",
];

